version: '3.7'
services:
  app:
    image: node:16.4.2-alpine
    container_name: grpc_app
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '50051:50051'
    volumes:
      - .:/usr/src/app
    links:
      - 'db:db'
    command: sh -c "apk add --no-cache ghostscript=9.53.3-r1 graphicsmagick=1.3.36-r0 && npm run start:dev"
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/